/*==============================================================*/
/* DBMS name:      MySQL 5.0                                    */
/* Created on:     22/09/2012 10:31:09 p.m.                     */
/*==============================================================*/


DROP TABLE IF EXISTS ACTIVIDAD;

DROP TABLE IF EXISTS ACTIVIDAD_SERVICIO;

DROP TABLE IF EXISTS CLIENTE;

DROP TABLE IF EXISTS COSTO_ACTIVIDAD;

DROP TABLE IF EXISTS COSTO_SERVICIO;

DROP TABLE IF EXISTS CUENTA;

DROP TABLE IF EXISTS DOCUMENTO;

DROP TABLE IF EXISTS EMPLEADO;

DROP TABLE IF EXISTS INDUCTOR_ACTIVIDAD;

DROP TABLE IF EXISTS PARTIDA;

DROP TABLE IF EXISTS PERFIL;

DROP TABLE IF EXISTS PERIODO;

DROP TABLE IF EXISTS PLANILLA;

DROP TABLE IF EXISTS SALDO;

DROP TABLE IF EXISTS SERVICIO;

DROP TABLE IF EXISTS SERVICIO_CLIENTE;

DROP TABLE IF EXISTS SUB_CUENTA;

DROP TABLE IF EXISTS TIPO_SERVICIO;

DROP TABLE IF EXISTS TRANSACCION;

DROP TABLE IF EXISTS USUARIO;

/*==============================================================*/
/* Table: ACTIVIDAD                                             */
/*==============================================================*/
CREATE TABLE ACTIVIDAD
(
   ID_ACTIVIDAD         CHAR(5) NOT NULL,
   ID_INDUCTOR_ACTIVIDAD CHAR(5) NOT NULL,
   NOMBRE_ACTIVIDAD     VARCHAR(50),
   DESCRIPCION_ACTIVIDAD VARCHAR(250),
   PRIMARY KEY (ID_ACTIVIDAD)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: ACTIVIDAD_SERVICIO                                    */
/*==============================================================*/
CREATE TABLE ACTIVIDAD_SERVICIO
(
   NUMERO_PERIODO       BIGINT NOT NULL,
   ID_ACTIVIDAD         CHAR(5) NOT NULL,
   ID_SERVICIO          CHAR(5) NOT NULL,
   FECHA_ACTIVIDAD_SERVICIO DATE,
   VALOR_INDUCTOR_ACTIVIDAD NUMERIC(8,2),
   NUMERO_REPETICIONES_ACTIVIDAD NUMERIC(8,2),
   DESCIPCION_ACTIVIDAD_SERVICIO VARCHAR(250),
   PRIMARY KEY (NUMERO_PERIODO, ID_ACTIVIDAD, ID_SERVICIO)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: CLIENTE                                               */
/*==============================================================*/
CREATE TABLE CLIENTE
(
   NUMERO_CLIENTE       BIGINT NOT NULL,
   PRIMER_NOMBRE_CLIENTE VARCHAR(50),
   SEGUNDO_NOMBRE_CLIENTE VARCHAR(50),
   PRIMER_APELLIDO_CLIENTE VARCHAR(50),
   SEGUNDO_APELLIDO_CLIENTE VARCHAR(50),
   TELEFONO_CLIENTE     CHAR(9),
   EMAIL_CLIENTE        VARCHAR(50),
   ESTADO_CLIENTE       BOOL,
   PRIMARY KEY (NUMERO_CLIENTE)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: COSTO_ACTIVIDAD                                       */
/*==============================================================*/
CREATE TABLE COSTO_ACTIVIDAD
(
   NUMERO_PERIODO       BIGINT NOT NULL,
   ID_ACTIVIDAD         CHAR(5) NOT NULL,
   VALOR_INDUCTOR_RECURSO NUMERIC(8,2),
   CIS_ACTIVIDAD        FLOAT(8,2),
   TOTAL_INDUCTOR_ACTIVIDAD NUMERIC(8,2),
   COSTO_ACTIVIDAD      FLOAT(8,2),
   PRIMARY KEY (NUMERO_PERIODO, ID_ACTIVIDAD)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: COSTO_SERVICIO                                        */
/*==============================================================*/
CREATE TABLE COSTO_SERVICIO
(
   ID_SERVICIO          CHAR(5) NOT NULL,
   NUMERO_PERIODO       BIGINT NOT NULL,
   COSTO_TOTAL_SERVICIO FLOAT(8,2),
   NUMERO_REPETICIONES_SERVICIO INT,
   COSTO_SERVICIO       FLOAT(8,2),
   PRIMARY KEY (ID_SERVICIO, NUMERO_PERIODO)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: CUENTA                                                */
/*==============================================================*/
CREATE TABLE CUENTA
(
   CODIGO_CUENTA        CHAR(5) NOT NULL,
   NOMBRE_CUENTA        VARCHAR(50),
   RUBRO_CUENTA         VARCHAR(50),
   SUBRUBRO_CUENTA      VARCHAR(50),
   TIPO_CUENTA          VARCHAR(20),
   DESCRIPCION_CUENTA   VARCHAR(150),
   SALDO_CUENTA         FLOAT(8,2),
   PRIMARY KEY (CODIGO_CUENTA)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: DOCUMENTO                                             */
/*==============================================================*/
CREATE TABLE DOCUMENTO
(
   ID_DOCUMENTO         CHAR(5) NOT NULL,
   NOMBRE_DOCUMENTO     VARCHAR(100),
   PRIMARY KEY (ID_DOCUMENTO)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: EMPLEADO                                              */
/*==============================================================*/
CREATE TABLE EMPLEADO
(
   ID_EMPLEADO          CHAR(5) NOT NULL,
   PRIMER_NOMBRE_EMPLEADO VARCHAR(50),
   SEGUNDO_NOMBRE_EMPLEADO VARCHAR(50),
   PRIMER_APELLIDO_EMPLEADO VARCHAR(50),
   SEGUNDO_APELLIDO_EMPLEADO VARCHAR(50),
   FECHA_CONTRATACION_EMPLEADO DATE,
   TELEFONO_EMPLEADO    CHAR(9),
   EMAIL_EMPLEADO       VARCHAR(50),
   ESTADO_EMPLEADO      BOOL,
   PRIMARY KEY (ID_EMPLEADO)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: INDUCTOR_ACTIVIDAD                                    */
/*==============================================================*/
CREATE TABLE INDUCTOR_ACTIVIDAD
(
   ID_INDUCTOR_ACTIVIDAD CHAR(5) NOT NULL,
   NOMBRE_INDUCTOR_ACTIVIDAD VARCHAR(50),
   DESCRIPCION_INDUCTOR_ACTIVIDAD VARCHAR(250),
   PRIMARY KEY (ID_INDUCTOR_ACTIVIDAD)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: PARTIDA                                               */
/*==============================================================*/
CREATE TABLE PARTIDA
(
   CORRELATIVO_PARTIDA  BIGINT NOT NULL,
   ID_DOCUMENTO         CHAR(5),
   FECHA_PARTIDA        DATE,
   NUMERO_DOCUMENTO     BIGINT,
   DESCRIPCION_PARTIDA  VARCHAR(150),
   TOTAL_DEBE           FLOAT(8,2),
   TOTAL_HABER          FLOAT(8,2),
   PRIMARY KEY (CORRELATIVO_PARTIDA)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: PERFIL                                                */
/*==============================================================*/
CREATE TABLE PERFIL
(
   ID_PERFIL            INT NOT NULL,
   NOMBRE_PERFIL        VARCHAR(15),
   PERMISO_REGISTRO_CONTABLE BOOL,
   PERMISO_REGISTRO_COSTO BOOL,
   PERMISO_LIBROS       BOOL,
   PERMISO_ESTADOS_FINANCIEROS BOOL,
   PERMISO_MANTENIMIENTO BOOL,
   PERMISO_ADMINISTRACION BOOL,
   PRIMARY KEY (ID_PERFIL)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: PERIODO                                               */
/*==============================================================*/
CREATE TABLE PERIODO
(
   NUMERO_PERIODO       BIGINT NOT NULL,
   FECHA_INICIO_PERIODO DATE,
   FECHA_FIN_PERIODO    DATE,
   ESTADO_PERIODO       BOOL,
   UTILIDADES_PERIODO   FLOAT(8,2),
   TOTAL_ACTIVO_PERIODO FLOAT(8,2),
   TOTAL_PASIVO_PERIODO FLOAT(8,2),
   TOTAL_CAPITAL_PERIODO FLOAT(8,2),
   TOTAL_GASTOS_PERIODO FLOAT(8,2),
   TOTAL_INGRESOS_PERIODO FLOAT(8,2),
   TOTAL_CIS_PERIODO    FLOAT(8,2),
   PRIMARY KEY (NUMERO_PERIODO)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: PLANILLA                                              */
/*==============================================================*/
CREATE TABLE PLANILLA
(
   NUMERO_PERIODO       BIGINT NOT NULL,
   ID_EMPLEADO          CHAR(5) NOT NULL,
   NUMERO_PLANILLA      BIGINT NOT NULL,
   SALARIO_BASE         FLOAT(8,2),
   NUMERO_HORAS_EXTRA   NUMERIC(2,2),
   HORAS_EXTRA          FLOAT(8,2),
   BONIFICACIONES       FLOAT(8,2),
   AFP                  FLOAT(8,2),
   ISSS                 FLOAT(8,2),
   SALARIO_NETO         FLOAT(8,2),
   PRIMARY KEY (NUMERO_PERIODO, ID_EMPLEADO)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: SALDO                                                 */
/*==============================================================*/
CREATE TABLE SALDO
(
   NUMERO_PERIODO       BIGINT NOT NULL,
   CODIGO_CUENTA        CHAR(5) NOT NULL,
   SALDO_FINAL_CUENTA   FLOAT(8,2),
   PRIMARY KEY (NUMERO_PERIODO, CODIGO_CUENTA)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: SERVICIO                                              */
/*==============================================================*/
CREATE TABLE SERVICIO
(
   ID_SERVICIO          CHAR(5) NOT NULL,
   NOMBRE_SERVICIO      VARCHAR(50),
   DESCRIPCION_SERVICIO VARCHAR(250),
   PRIMARY KEY (ID_SERVICIO)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: SERVICIO_CLIENTE                                      */
/*==============================================================*/
CREATE TABLE SERVICIO_CLIENTE
(
   ID_TIPO_SERVICIO     CHAR(5) NOT NULL,
   NUMERO_CLIENTE       BIGINT NOT NULL,
   NUMERO_PERIODO       BIGINT NOT NULL,
   FECHA_SERVICIO_CLIENTE DATE,
   TERMINOS_SERVICIO_CLIENTE VARCHAR(500),
   PRIMARY KEY (ID_TIPO_SERVICIO, NUMERO_CLIENTE, NUMERO_PERIODO)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: SUB_CUENTA                                            */
/*==============================================================*/
CREATE TABLE SUB_CUENTA
(
   CODIGO_SUBCUENTA     CHAR(7) NOT NULL,
   CODIGO_CUENTA        CHAR(5) NOT NULL,
   NOMBRE_SUBCUENTA     VARCHAR(50),
   DESCRIPCION_SUBCUENTA VARCHAR(150),
   SALDO_SUBCUENTA      FLOAT(8,2),
   PRIMARY KEY (CODIGO_SUBCUENTA)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: TIPO_SERVICIO                                         */
/*==============================================================*/
CREATE TABLE TIPO_SERVICIO
(
   ID_TIPO_SERVICIO     CHAR(5) NOT NULL,
   ID_SERVICIO          CHAR(5) NOT NULL,
   NOMBRE_TIPO_SERVICIO VARCHAR(100),
   DESCRIPCION_TIPO_SERVICIO VARCHAR(250),
   PRIMARY KEY (ID_TIPO_SERVICIO)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: TRANSACCION                                           */
/*==============================================================*/
CREATE TABLE TRANSACCION
(
   CORRELATIVO_PARTIDA  BIGINT NOT NULL,
   NUMERO_PERIODO       BIGINT NOT NULL,
   CODIGO_SUBCUENTA     CHAR(7) NOT NULL,
   DEBE                 FLOAT(8,2),
   HABER                FLOAT(8,2),
   PRIMARY KEY (CORRELATIVO_PARTIDA, NUMERO_PERIODO, CODIGO_SUBCUENTA)
)
TYPE = MYISAM;

/*==============================================================*/
/* Table: USUARIO                                               */
/*==============================================================*/
CREATE TABLE USUARIO
(
   ID_USUARIO           CHAR(5) NOT NULL,
   ID_PERFIL            INT NOT NULL,
   PRIMER_NOMBRE_USUARIO VARCHAR(50),
   SEGUNDO_NOMBRE_USUARIO VARCHAR(50),
   PRIMER_APELLIDO_USUARIO VARCHAR(50),
   SEGUNDO_APELLIDO_USUARIO VARCHAR(50),
   CONTRASENA_USUARIO   VARCHAR(10),
   PRIMARY KEY (ID_USUARIO)
)
TYPE = MYISAM;

ALTER TABLE ACTIVIDAD ADD CONSTRAINT FK_ACTIVIDAD_TIENE_INDUCTOR FOREIGN KEY (ID_INDUCTOR_ACTIVIDAD)
      REFERENCES INDUCTOR_ACTIVIDAD (ID_INDUCTOR_ACTIVIDAD) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ACTIVIDAD_SERVICIO ADD CONSTRAINT FK_ACTIVIDAD_SERVICIO FOREIGN KEY (NUMERO_PERIODO)
      REFERENCES PERIODO (NUMERO_PERIODO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ACTIVIDAD_SERVICIO ADD CONSTRAINT FK_ACTIVIDAD_SERVICIO2 FOREIGN KEY (ID_ACTIVIDAD)
      REFERENCES ACTIVIDAD (ID_ACTIVIDAD) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE ACTIVIDAD_SERVICIO ADD CONSTRAINT FK_ACTIVIDAD_SERVICIO3 FOREIGN KEY (ID_SERVICIO)
      REFERENCES SERVICIO (ID_SERVICIO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE COSTO_ACTIVIDAD ADD CONSTRAINT FK_COSTO_ACTIVIDAD FOREIGN KEY (NUMERO_PERIODO)
      REFERENCES PERIODO (NUMERO_PERIODO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE COSTO_ACTIVIDAD ADD CONSTRAINT FK_COSTO_ACTIVIDAD2 FOREIGN KEY (ID_ACTIVIDAD)
      REFERENCES ACTIVIDAD (ID_ACTIVIDAD) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE COSTO_SERVICIO ADD CONSTRAINT FK_COSTO_SERVICIO FOREIGN KEY (ID_SERVICIO)
      REFERENCES SERVICIO (ID_SERVICIO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE COSTO_SERVICIO ADD CONSTRAINT FK_COSTO_SERVICIO2 FOREIGN KEY (NUMERO_PERIODO)
      REFERENCES PERIODO (NUMERO_PERIODO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PARTIDA ADD CONSTRAINT FK_PARTIDA_TIENE_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO)
      REFERENCES DOCUMENTO (ID_DOCUMENTO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PLANILLA ADD CONSTRAINT FK_PLANILLA FOREIGN KEY (NUMERO_PERIODO)
      REFERENCES PERIODO (NUMERO_PERIODO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE PLANILLA ADD CONSTRAINT FK_PLANILLA2 FOREIGN KEY (ID_EMPLEADO)
      REFERENCES EMPLEADO (ID_EMPLEADO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE SALDO ADD CONSTRAINT FK_SALDO FOREIGN KEY (NUMERO_PERIODO)
      REFERENCES PERIODO (NUMERO_PERIODO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE SALDO ADD CONSTRAINT FK_SALDO2 FOREIGN KEY (CODIGO_CUENTA)
      REFERENCES CUENTA (CODIGO_CUENTA) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE SERVICIO_CLIENTE ADD CONSTRAINT FK_SERVICIO_CLIENTE FOREIGN KEY (ID_TIPO_SERVICIO)
      REFERENCES TIPO_SERVICIO (ID_TIPO_SERVICIO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE SERVICIO_CLIENTE ADD CONSTRAINT FK_SERVICIO_CLIENTE2 FOREIGN KEY (NUMERO_CLIENTE)
      REFERENCES CLIENTE (NUMERO_CLIENTE) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE SERVICIO_CLIENTE ADD CONSTRAINT FK_SERVICIO_CLIENTE3 FOREIGN KEY (NUMERO_PERIODO)
      REFERENCES PERIODO (NUMERO_PERIODO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE SUB_CUENTA ADD CONSTRAINT FK_CUENTA_TIENE_SUBCUENTA FOREIGN KEY (CODIGO_CUENTA)
      REFERENCES CUENTA (CODIGO_CUENTA) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TIPO_SERVICIO ADD CONSTRAINT FK_SERVICIO_TIENE_TIPO_SERVICIO FOREIGN KEY (ID_SERVICIO)
      REFERENCES SERVICIO (ID_SERVICIO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TRANSACCION ADD CONSTRAINT FK_TRANSACCION FOREIGN KEY (CORRELATIVO_PARTIDA)
      REFERENCES PARTIDA (CORRELATIVO_PARTIDA) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TRANSACCION ADD CONSTRAINT FK_TRANSACCION2 FOREIGN KEY (NUMERO_PERIODO)
      REFERENCES PERIODO (NUMERO_PERIODO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TRANSACCION ADD CONSTRAINT FK_TRANSACCION3 FOREIGN KEY (CODIGO_SUBCUENTA)
      REFERENCES SUB_CUENTA (CODIGO_SUBCUENTA) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_TIENE_PERFIL FOREIGN KEY (ID_PERFIL)
      REFERENCES PERFIL (ID_PERFIL) ON DELETE RESTRICT ON UPDATE RESTRICT;

